name: "Build and Export Game"
on:
  pull_request:
  push:
    branches:
      - "*"
  workflow_dispatch:

# Cancel any ongoing previous run if the job is re-triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - uses: endlessm/godot-export-action@v1
        with:
          godot_version: 4.5.1

      - name: Upload web artifact
        uses: actions/upload-artifact@v6
        with:
          name: web
          path: build/web
